apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-series
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /srv/pv/plex-movies
